plugins:
  - jekyll-feed
  - jekyll-sitemap

# SEO Stuff
author: Fosstodon
description: Fosstodon Hub is an informational site tied to Fosstodon, the largest FOSS focussed Mastodon instance on the fediverse.
lang: en
locale: en_GB
url: "https://hub.fosstodon.org"
baseurl: ""
permalink: :title

# RSS feeds
feed:
  posts_limit: 20

# Netlify redirects
include:
  - _redirects
